plugin:
    name: 'nvandendriesdev.planning::lang.plugin.name'
    description: 'nvandendriesdev.planning::lang.plugin.description'
    author: NvandenDries.dev
    icon: oc-icon-calendar
    homepage: 'https://nvandendries.dev'
permissions:
    planning_beheerder:
        tab: 'nvandendriesdev.planning::lang.plugin.description'
        label: 'Planning beheer'
    development_beheerder:
        tab: 'nvandendriesdev.planning::lang.plugin.description'
        label: 'Development beheer'
    tapkasten_beheerder:
        tab: 'nvandendriesdev.planning::lang.plugin.description'
        label: 'Tapkasten beheer'
    Leaflet:
        tab: 'nvandendriesdev.planning::lang.plugin.description'
        label: 'Maps beheer'
    werkbonnen_beheerder:
        tab: 'nvandendriesdev.planning::lang.plugin.description'
        label: 'Werkbonnen beheer'
navigation:
    main-menu-item:
        label: 'OmitCentral Toolkit'
        url: /
        icon: icon-wrench
        permissions:
            - planning_beheerder
            - tapkasten_beheerder
            - development_beheerder
        sideMenu:
            side-menu-item:
                label: 'Klant Afspraken'
                url: nvandendriesdev/planning/afspraken
                icon: icon-calendar
                permissions:
                    - planning_beheerder
            side-menu-item2:
                label: 'Tapkasten Bewerken'
                url: nvandendriesdev/planning/tapkasten
                icon: icon-location-arrow
                permissions:
                    - tapkasten_beheerder
            side-menu-item3:
                label: Development
                url: nvandendriesdev/planning/developmentstatus
                icon: icon-gears
                permissions:
                    - development_beheerder
            side-menu-item4:
                label: Werkbonnen
                url: nvandendriesdev/planning/werkbonnen
                icon: icon-paper-plane-o
                permissions:
                    - werkbonnen_beheerder
