title: Tapkasten
modelClass: NvandendriesDev\Planning\Models\Tapkasten
list: $/nvandendriesdev/planning/models/tapkasten/columns.yaml
recordUrl: 'nvandendriesdev/planning/tapkasten/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
