title: Afspraken
modelClass: NvandendriesDev\Planning\Models\Afspraak
list: $/nvandendriesdev/planning/models/afspraak/columns.yaml
recordUrl: 'nvandendriesdev/planning/afspraken/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
