title: DevelopmentStatus
modelClass: NvandendriesDev\Planning\Models\DevelopmentStatus
list: $/nvandendriesdev/planning/models/developmentstatus/columns.yaml
recordUrl: 'nvandendriesdev/planning/developmentstatus/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
