title: Werkbonnen
modelClass: NvandendriesDev\Planning\Models\Werkbonnen
list: $/nvandendriesdev/planning/models/werkbonnen/columns.yaml
recordUrl: 'nvandendriesdev/planning/werkbonnen/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
